services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # No ports section here!
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`localhost`)"
      - "traefik.http.routers.app.entrypoints=api"
      - "traefik.http.services.app.loadbalancer.server.port=80"

  traefik:
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.api.address=:8081"
      - "--entrypoints.dashboard.address=:8080"
    ports:
      - "8081:8081"   # API exposed here
      - "8080:8080"   # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped