"""Shared attributes for all models."""

SCHEMA = "dbo"
TABLE_ARGS = {"schema": SCHEMA}


# Table names
TABLE_NAME_PART = "PART"
TABLE_NAME_WORK_ORDER = "WORK_ORDER"
TABLE_NAME_CUSTOMER = "CUSTOMER"
TABLE_NAME_CUSTOMER_ORDER = "CUSTOMER_ORDER"
TABLE_NAME_CUSTOMER_ORDER_LINE = "CUST_ORDER_LINE"
TABLE_NAME_CURRENCY = "CURRENCY"
TABLE_NAME_SITE = "SITE"
TABLE_NAME_UNIT_OF_MEASURE = "UNIT_OF_MEASURE"
